### ISSUE TITLE
因为移动文档目录导致的问题

### ISSUE THREAD

**Issue by xczing** [yunlongzhuhuo/Windows-WeChat-Clean-Up-Tool#1]
![image](https://user-images.githubusercontent.com/70993225/152080728-0b22cba9-e33e-409e-bc6c-cea0969652e2.png)
我将user文件夹下的Documents目录转移到了D盘的userdata目录下，然后就报错了

**Comment by yunlongzhuhuo** [comment]
这个问题我想了半天，已经修好了，一会pull新版本
